---
- name: Gather one specific VM
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ inventory_hostname }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter_name }}"
    folder: "{{ VM_Folder }}"
  delegate_to: localhost
  register: vm_info
  until: vm_info.instance.hw_power_status is defined and vm_info.instance.hw_power_status == 'poweredOn'
  retries: 10
  delay: 10